Add observable to Desmo module
vaimee/desmo-sdk pull request #22
Opened 2022-09-20 16:26 UTC by iosonopersia

Adds an observable to Desmo module so that the frontend can be notified about the execution state of the query.
The observable payload contains both the taskID (it could be used by the frontend to show a link to the iExec task) and a string representing the updated status of the task.

2022-09-20 16:49 UTC, relu91 requested changes

2022-09-20 16:49 UTC, relu91 commented on src/lib/desmo-module.ts
> +  queryState$: Observable<IQueryState>;
Trasform this into a getter

2022-09-20 17:01 UTC, iosonopersia commented on src/lib/desmo-module.ts
> +  queryState$: Observable<IQueryState>;
Done.

2022-09-23 10:16 UTC, relu91 approved these changes

2022-09-23 10:16 UTC, merged